language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t josemvcerqueira/docker-basic -f Dockerfile.dev .

script:
  - docker run -e CI=true josemvcerqueira/docker-basic npm run test
